routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/connexion', 'App\Http\Controllers\AdminController@connexion');
Route::post('/connexion', 'App\Http\Controllers\AdminController@login')->name('connecter');
Route::get('/inscription', 'App\Http\Controllers\AdminController@inscription');
Route::post('/inscription_store', 'App\Http\Controllers\AdminController@inscription_store')->name('inscription_store');

Route::group(['middleware' => 'Connecter'], function(){
    Route::get('/admin/dashboard', 'App\Http\Controllers\AdminController@dashboard');

    Route::get('/mes-parcours', 'App\Http\Controllers\ParcourFormationController@mes_parcours');
    Route::get('/creation-parcours-formation', 'App\Http\Controllers\ParcourFormationController@create_parcours');
    Route::get('/creation-parcours-formation-activite', 'App\Http\Controllers\ParcourFormationController@create_parcours_activite');
    Route::post('/creation-parcours-formationStore', 'App\Http\Controllers\ParcourFormationController@store_parcours')->name('store_parcours_formation');

    Route::get('/mes-activites', 'App\Http\Controllers\ActiviteController@mes_activites');
    Route::get('/creation-activites', 'App\Http\Controllers\ActiviteController@create_activites');
    Route::post('/creation-activitesStore', 'App\Http\Controllers\ActiviteController@store_activites')->name('store_activites');

    Route::delete('/suprime-activites/{id}', 'App\Http\Controllers\ActiviteController@destroy_activites')->name('delete_activites');
    Route::delete('/suprime-parcours/{id}', 'App\Http\Controllers\ParcourFormationController@destroy_parcour')->name('delete_parcour');
});

Route::get('/', function () {
    return view('login');
});
Route::get('/login', function () {
    return view('login');
});
Route::get('/login1', function () {
    return view('login1');
});
Route::get('/register', function () {
    return view('register');
});
Route::get('/forgetPasswoord', function () {
    return view('forgetPasswoord');
});

Route::get('/reset-code-promo', function () {
    $users = DB::table('users')->get();
     
    foreach($users as $user)
    {
        // generate a pin based on 2 * 2 digits + a random character
        $code_rand = mt_rand(10, 99)
                   . mt_rand(10, 99);
       
        //shuffle the result
        $uni_prenom = substr($user->prenom, 0, 1);
        $uni_nom = substr($user->nom, 0, 1);
        $code = strtoupper($uni_nom) . strtoupper($uni_prenom) . $code_rand;

        DB::table('users')->where('id', $user->id)->update(['code_promo' => $code]);
    }
    dd('code promo reset for all users successfully !');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('apprenants', App\Http\Controllers\ApprenantController::class);

Route::resource('/certifications', App\Http\Controllers\CertificationsController::class);

Route::resource('canvaMiniDisqs', App\Http\Controllers\CanvaMiniDisqController::class);

Route::resource('points', App\Http\Controllers\PointsController::class);

Route::resource('passerTests', App\Http\Controllers\PasserTestController::class);


Route::resource('questions', App\Http\Controllers\QuestionController::class);


Route::resource('domaines', App\Http\Controllers\DomaineController::class);


Route::resource('miniDisqs', App\Http\Controllers\MiniDisqController::class);


Route::resource('responses', App\Http\Controllers\ResponseController::class);


Route::resource('responseByUserDiscs', App\Http\Controllers\ResponseByUserDiscController::class);


Route::resource('roueVies', App\Http\Controllers\RoueVieController::class);


Route::resource('responseByUsers', App\Http\Controllers\ResponseByUserController::class);


Route::resource('apprenantDomains', App\Http\Controllers\ApprenantDomainController::class);


Route::resource('caracteristiques', App\Http\Controllers\CaracteristiqueController::class);


Route::resource('videos', App\Http\Controllers\VideoController::class);


Route::resource('audio', App\Http\Controllers\AudioController::class);


Route::resource('articles', App\Http\Controllers\ArticleController::class);


Route::resource('parcoursFormations', App\Http\Controllers\ParcoursFormationController::class);


Route::resource('quizzs', App\Http\Controllers\QuizzController::class);


Route::resource('responsesQuizzs', App\Http\Controllers\ResponsesQuizzController::class);


Route::resource('questionsQuizzs', App\Http\Controllers\QuestionsQuizzController::class);


Route::resource('responseUserQuizzs', App\Http\Controllers\ResponseUserQuizzController::class);


Route::resource('challenges', App\Http\Controllers\challengeController::class);


Route::resource('questionChallenges', App\Http\Controllers\QuestionChallengeController::class);


Route::resource('responseUserChallenges', App\Http\Controllers\ResponseUserChallengeController::class);


Route::resource('commentaires', App\Http\Controllers\CommentaireController::class);


Route::resource('citations', App\Http\Controllers\CitationController::class);



Route::resource('sentMails', App\Http\Controllers\SentMailController::class);


Route::resource('validationEmails', App\Http\Controllers\ValidationEmailController::class);


Route::resource('apprenantCompetences', App\Http\Controllers\ApprenantCompetenceController::class);


Route::resource('competences', App\Http\Controllers\CompetenceController::class);


Route::resource('podcasts', App\Http\Controllers\PodcastController::class);


Route::resource('parcourActivites', App\Http\Controllers\ParcourActiviteController::class);

app/Models/ValidationEmail.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class ValidationEmail
 * @package App\Models
 * @version January 5, 2023, 6:35 pm UTC
 *
 * @property integer $code
 * @property unsignedInteger $user_id
 * @property string $email
 */
class ValidationEmail extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'validation_emails';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'code',
        'email'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'code' => 'integer',
        'email' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'code' => 'required',
        'email' => 'required'
    ];

    
}

app/Http/Controllers/ValidationEmailController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateValidationEmailRequest;
use App\Http\Requests\UpdateValidationEmailRequest;
use App\Http\Controllers\AppBaseController;
use App\Models\ValidationEmail;
use Illuminate\Http\Request;
use Flash;
use Response;

class ValidationEmailController extends AppBaseController
{
    /**
     * Display a listing of the ValidationEmail.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        /** @var ValidationEmail $validationEmails */
        $validationEmails = ValidationEmail::all();

        return view('validation_emails.index')
            ->with('validationEmails', $validationEmails);
    }

    /**
     * Show the form for creating a new ValidationEmail.
     *
     * @return Response
     */
    public function create()
    {
        return view('validation_emails.create');
    }

    /**
     * Store a newly created ValidationEmail in storage.
     *
     * @param CreateValidationEmailRequest $request
     *
     * @return Response
     */
    public function store(CreateValidationEmailRequest $request)
    {
        $input = $request->all();

        /** @var ValidationEmail $validationEmail */
        $validationEmail = ValidationEmail::create($input);

        Flash::success('Validation Email saved successfully.');

        return redirect(route('validationEmails.index'));
    }

    /**
     * Display the specified ValidationEmail.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var ValidationEmail $validationEmail */
        $validationEmail = ValidationEmail::find($id);

        if (empty($validationEmail)) {
            Flash::error('Validation Email not found');

            return redirect(route('validationEmails.index'));
        }

        return view('validation_emails.show')->with('validationEmail', $validationEmail);
    }

    /**
     * Show the form for editing the specified ValidationEmail.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var ValidationEmail $validationEmail */
        $validationEmail = ValidationEmail::find($id);

        if (empty($validationEmail)) {
            Flash::error('Validation Email not found');

            return redirect(route('validationEmails.index'));
        }

        return view('validation_emails.edit')->with('validationEmail', $validationEmail);
    }

    /**
     * Update the specified ValidationEmail in storage.
     *
     * @param int $id
     * @param UpdateValidationEmailRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateValidationEmailRequest $request)
    {
        /** @var ValidationEmail $validationEmail */
        $validationEmail = ValidationEmail::find($id);

        if (empty($validationEmail)) {
            Flash::error('Validation Email not found');

            return redirect(route('validationEmails.index'));
        }

        $validationEmail->fill($request->all());
        $validationEmail->save();

        Flash::success('Validation Email updated successfully.');

        return redirect(route('validationEmails.index'));
    }

    /**
     * Remove the specified ValidationEmail from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var ValidationEmail $validationEmail */
        $validationEmail = ValidationEmail::find($id);

        if (empty($validationEmail)) {
            Flash::error('Validation Email not found');

            return redirect(route('validationEmails.index'));
        }

        $validationEmail->delete();

        Flash::success('Validation Email deleted successfully.');

        return redirect(route('validationEmails.index'));
    }
}

resources/views/validation_emails/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Validation Email</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'validationEmails.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('validation_emails.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('validationEmails.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/validation_emails/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Validation Email</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($validationEmail, ['route' => ['validationEmails.update', $validationEmail->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('validation_emails.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('validationEmails.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/validation_emails/fields.blade.php
<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

resources/views/validation_emails/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Validation Emails</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('validationEmails.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('validation_emails.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/validation_emails/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Validation Email Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('validationEmails.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('validation_emails.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/validation_emails/show_fields.blade.php
<!-- Code Field -->
<div class="col-sm-12">
    {!! Form::label('code', 'Code:') !!}
    <p>{{ $validationEmail->code }}</p>
</div>

<!-- User Id Field -->
<div class="col-sm-12">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{{ $validationEmail->user_id }}</p>
</div>

<!-- Email Field -->
<div class="col-sm-12">
    {!! Form::label('email', 'Email:') !!}
    <p>{{ $validationEmail->email }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $validationEmail->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $validationEmail->updated_at }}</p>
</div>

resources/views/validation_emails/table.blade.php
<div class="table-responsive">
    <table class="table" id="validationEmails-table">
        <thead>
        <tr>
            <th>Code</th>
        <th>User Id</th>
        <th>Email</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($validationEmails as $validationEmail)
            <tr>
                <td>{{ $validationEmail->code }}</td>
            <td>{{ $validationEmail->user_id }}</td>
            <td>{{ $validationEmail->email }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['validationEmails.destroy', $validationEmail->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('validationEmails.show', [$validationEmail->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('validationEmails.edit', [$validationEmail->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>