routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/connexion', 'App\Http\Controllers\AdminController@connexion');
Route::post('/connexion', 'App\Http\Controllers\AdminController@login')->name('connecter');
Route::get('/inscription', 'App\Http\Controllers\AdminController@inscription');
Route::post('/inscription_store', 'App\Http\Controllers\AdminController@inscription_store')->name('inscription_store');

Route::group(['middleware' => 'Connecter'], function(){
    Route::get('/admin/dashboard', 'App\Http\Controllers\AdminController@dashboard');

    Route::get('/mes-parcours', 'App\Http\Controllers\ParcourFormationController@mes_parcours');
    Route::get('/creation-parcours-formation', 'App\Http\Controllers\ParcourFormationController@create_parcours');
    Route::get('/creation-parcours-formation-activite', 'App\Http\Controllers\ParcourFormationController@create_parcours_activite');
    Route::post('/creation-parcours-formationStore', 'App\Http\Controllers\ParcourFormationController@store_parcours')->name('store_parcours_formation');

    Route::get('/mes-activites', 'App\Http\Controllers\ActiviteController@mes_activites');
    Route::get('/creation-activites', 'App\Http\Controllers\ActiviteController@create_activites');
    Route::post('/creation-activitesStore', 'App\Http\Controllers\ActiviteController@store_activites')->name('store_activites');

    Route::delete('/suprime-activites/{id}', 'App\Http\Controllers\ActiviteController@destroy_activites')->name('delete_activites');
    Route::delete('/suprime-parcours/{id}', 'App\Http\Controllers\ParcourFormationController@destroy_parcour')->name('delete_parcour');
});

Route::get('/', function () {
    return view('login');
});
Route::get('/login', function () {
    return view('login');
});
Route::get('/login1', function () {
    return view('login1');
});
Route::get('/register', function () {
    return view('register');
});
Route::get('/forgetPasswoord', function () {
    return view('forgetPasswoord');
});

Route::get('/reset-code-promo', function () {
    $users = DB::table('users')->get();
     
    foreach($users as $user)
    {
        // generate a pin based on 2 * 2 digits + a random character
        $code_rand = mt_rand(10, 99)
                   . mt_rand(10, 99);
       
        //shuffle the result
        $uni_prenom = substr($user->prenom, 0, 1);
        $uni_nom = substr($user->nom, 0, 1);
        $code = strtoupper($uni_nom) . strtoupper($uni_prenom) . $code_rand;

        DB::table('users')->where('id', $user->id)->update(['code_promo' => $code]);
    }
    dd('code promo reset for all users successfully !');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('apprenants', App\Http\Controllers\ApprenantController::class);

Route::resource('/certifications', App\Http\Controllers\CertificationsController::class);

Route::resource('canvaMiniDisqs', App\Http\Controllers\CanvaMiniDisqController::class);

Route::resource('points', App\Http\Controllers\PointsController::class);

Route::resource('passerTests', App\Http\Controllers\PasserTestController::class);


Route::resource('questions', App\Http\Controllers\QuestionController::class);


Route::resource('domaines', App\Http\Controllers\DomaineController::class);


Route::resource('miniDisqs', App\Http\Controllers\MiniDisqController::class);


Route::resource('responses', App\Http\Controllers\ResponseController::class);


Route::resource('responseByUserDiscs', App\Http\Controllers\ResponseByUserDiscController::class);


Route::resource('roueVies', App\Http\Controllers\RoueVieController::class);


Route::resource('responseByUsers', App\Http\Controllers\ResponseByUserController::class);


Route::resource('apprenantDomains', App\Http\Controllers\ApprenantDomainController::class);


Route::resource('caracteristiques', App\Http\Controllers\CaracteristiqueController::class);


Route::resource('videos', App\Http\Controllers\VideoController::class);


Route::resource('audio', App\Http\Controllers\AudioController::class);


Route::resource('articles', App\Http\Controllers\ArticleController::class);


Route::resource('parcoursFormations', App\Http\Controllers\ParcoursFormationController::class);


Route::resource('quizzs', App\Http\Controllers\QuizzController::class);


Route::resource('responsesQuizzs', App\Http\Controllers\ResponsesQuizzController::class);


Route::resource('questionsQuizzs', App\Http\Controllers\QuestionsQuizzController::class);


Route::resource('responseUserQuizzs', App\Http\Controllers\ResponseUserQuizzController::class);


Route::resource('challenges', App\Http\Controllers\challengeController::class);


Route::resource('questionChallenges', App\Http\Controllers\QuestionChallengeController::class);


Route::resource('responseUserChallenges', App\Http\Controllers\ResponseUserChallengeController::class);


Route::resource('commentaires', App\Http\Controllers\CommentaireController::class);


Route::resource('citations', App\Http\Controllers\CitationController::class);



Route::resource('sentMails', App\Http\Controllers\SentMailController::class);


Route::resource('validationEmails', App\Http\Controllers\ValidationEmailController::class);


Route::resource('apprenantCompetences', App\Http\Controllers\ApprenantCompetenceController::class);


Route::resource('competences', App\Http\Controllers\CompetenceController::class);


Route::resource('podcasts', App\Http\Controllers\PodcastController::class);


Route::resource('parcourActivites', App\Http\Controllers\ParcourActiviteController::class);

app/Models/Parcours_formation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Parcours_formation extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    public $table = 'parcours_formations';

    public $fillable = [
        'libelle',
        'description',
        'prix',
        'prix_promo',
        'duree',
        'win_points',
        'require_credits',
        'formateur_id',
        'parcours_transformation_id'
    ];

     /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
    ];

    public function certifications()
    {
        return $this->hasMany('App\Models\Certification');
    }
}

app/Http/Controllers/ParcoursFormationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateParcoursFormationRequest;
use App\Http\Requests\UpdateParcoursFormationRequest;
use App\Http\Controllers\AppBaseController;
use App\Models\ParcoursFormation;
use Illuminate\Http\Request;
use Flash;
use Response;

class ParcoursFormationController extends AppBaseController
{
    /**
     * Display a listing of the ParcoursFormation.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        /** @var ParcoursFormation $parcoursFormations */
        $parcoursFormations = ParcoursFormation::all();

        return view('parcours_formations.index')
            ->with('parcoursFormations', $parcoursFormations);
    }

    /**
     * Show the form for creating a new ParcoursFormation.
     *
     * @return Response
     */
    public function create()
    {
        return view('parcours_formations.create');
    }

    /**
     * Store a newly created ParcoursFormation in storage.
     *
     * @param CreateParcoursFormationRequest $request
     *
     * @return Response
     */
    public function store(CreateParcoursFormationRequest $request)
    {
        $input = $request->all();

        /** @var ParcoursFormation $parcoursFormation */
        $parcoursFormation = ParcoursFormation::create($input);

        Flash::success('Parcours Formation saved successfully.');

        return redirect(route('parcoursFormations.index'));
    }

    /**
     * Display the specified ParcoursFormation.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var ParcoursFormation $parcoursFormation */
        $parcoursFormation = ParcoursFormation::find($id);

        if (empty($parcoursFormation)) {
            Flash::error('Parcours Formation not found');

            return redirect(route('parcoursFormations.index'));
        }

        return view('parcours_formations.show')->with('parcoursFormation', $parcoursFormation);
    }

    /**
     * Show the form for editing the specified ParcoursFormation.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var ParcoursFormation $parcoursFormation */
        $parcoursFormation = ParcoursFormation::find($id);

        if (empty($parcoursFormation)) {
            Flash::error('Parcours Formation not found');

            return redirect(route('parcoursFormations.index'));
        }

        return view('parcours_formations.edit')->with('parcoursFormation', $parcoursFormation);
    }

    /**
     * Update the specified ParcoursFormation in storage.
     *
     * @param int $id
     * @param UpdateParcoursFormationRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateParcoursFormationRequest $request)
    {
        /** @var ParcoursFormation $parcoursFormation */
        $parcoursFormation = ParcoursFormation::find($id);

        if (empty($parcoursFormation)) {
            Flash::error('Parcours Formation not found');

            return redirect(route('parcoursFormations.index'));
        }

        $parcoursFormation->fill($request->all());
        $parcoursFormation->save();

        Flash::success('Parcours Formation updated successfully.');

        return redirect(route('parcoursFormations.index'));
    }

    /**
     * Remove the specified ParcoursFormation from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var ParcoursFormation $parcoursFormation */
        $parcoursFormation = ParcoursFormation::find($id);

        if (empty($parcoursFormation)) {
            Flash::error('Parcours Formation not found');

            return redirect(route('parcoursFormations.index'));
        }

        $parcoursFormation->delete();

        Flash::success('Parcours Formation deleted successfully.');

        return redirect(route('parcoursFormations.index'));
    }
}

resources/views/parcours_formations/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Parcours Formation</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'parcoursFormations.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('parcours_formations.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('parcoursFormations.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/parcours_formations/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Parcours Formation</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($parcoursFormation, ['route' => ['parcoursFormations.update', $parcoursFormation->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('parcours_formations.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('parcoursFormations.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/parcours_formations/fields.blade.php
<!-- Libelle Field -->
<div class="form-group col-sm-6">
    {!! Form::label('libelle', 'Libelle:') !!}
    {!! Form::text('libelle', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

resources/views/parcours_formations/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Parcours Formations</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('parcoursFormations.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('parcours_formations.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/parcours_formations/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Parcours Formation Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('parcoursFormations.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('parcours_formations.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/parcours_formations/show_fields.blade.php
<!-- Libelle Field -->
<div class="col-sm-12">
    {!! Form::label('libelle', 'Libelle:') !!}
    <p>{{ $parcoursFormation->libelle }}</p>
</div>

<!-- Description Field -->
<div class="col-sm-12">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $parcoursFormation->description }}</p>
</div>

<!-- Prix Field -->
<div class="col-sm-12">
    {!! Form::label('prix', 'Prix:') !!}
    <p>{{ $parcoursFormation->prix }}</p>
</div>

<!-- Duree Field -->
<div class="col-sm-12">
    {!! Form::label('duree', 'Duree:') !!}
    <p>{{ $parcoursFormation->duree }}</p>
</div>

<!-- Formateur Id Field -->
<div class="col-sm-12">
    {!! Form::label('formateur_id', 'Formateur Id:') !!}
    <p>{{ $parcoursFormation->formateur_id }}</p>
</div>

<!-- Parcours Transformation Id Field -->
<div class="col-sm-12">
    {!! Form::label('parcours_transformation_id', 'Parcours Transformation Id:') !!}
    <p>{{ $parcoursFormation->parcours_transformation_id }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $parcoursFormation->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $parcoursFormation->updated_at }}</p>
</div>

resources/views/parcours_formations/table.blade.php
<div class="table-responsive">
    <table class="table" id="parcoursFormations-table">
        <thead>
        <tr>
            <th>Libelle</th>
        <th>Description</th>
        <th>Prix</th>
        <th>Duree</th>
        <th>Formateur Id</th>
        <th>Parcours Transformation Id</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($parcoursFormations as $parcoursFormation)
            <tr>
                <td>{{ $parcoursFormation->libelle }}</td>
            <td>{{ $parcoursFormation->description }}</td>
            <td>{{ $parcoursFormation->prix }}</td>
            <td>{{ $parcoursFormation->duree }}</td>
            <td>{{ $parcoursFormation->formateur_id }}</td>
            <td>{{ $parcoursFormation->parcours_transformation_id }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['parcoursFormations.destroy', $parcoursFormation->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('parcoursFormations.show', [$parcoursFormation->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('parcoursFormations.edit', [$parcoursFormation->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>