routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/connexion', 'App\Http\Controllers\AdminController@connexion');
Route::post('/connexion', 'App\Http\Controllers\AdminController@login')->name('connecter');
Route::get('/inscription', 'App\Http\Controllers\AdminController@inscription');
Route::post('/inscription_store', 'App\Http\Controllers\AdminController@inscription_store')->name('inscription_store');

Route::group(['middleware' => 'Connecter'], function(){
    Route::get('/admin/dashboard', 'App\Http\Controllers\AdminController@dashboard');

    Route::get('/mes-parcours', 'App\Http\Controllers\ParcourFormationController@mes_parcours');
    Route::get('/creation-parcours-formation', 'App\Http\Controllers\ParcourFormationController@create_parcours');
    Route::get('/creation-parcours-formation-activite', 'App\Http\Controllers\ParcourFormationController@create_parcours_activite');
    Route::post('/creation-parcours-formationStore', 'App\Http\Controllers\ParcourFormationController@store_parcours')->name('store_parcours_formation');

    Route::get('/mes-activites', 'App\Http\Controllers\ActiviteController@mes_activites');
    Route::get('/creation-activites', 'App\Http\Controllers\ActiviteController@create_activites');
    Route::post('/creation-activitesStore', 'App\Http\Controllers\ActiviteController@store_activites')->name('store_activites');

    Route::delete('/suprime-activites/{id}', 'App\Http\Controllers\ActiviteController@destroy_activites')->name('delete_activites');
    Route::delete('/suprime-parcours/{id}', 'App\Http\Controllers\ParcourFormationController@destroy_parcour')->name('delete_parcour');
});

Route::get('/', function () {
    return view('login');
});
Route::get('/login', function () {
    return view('login');
});
Route::get('/login1', function () {
    return view('login1');
});
Route::get('/register', function () {
    return view('register');
});
Route::get('/forgetPasswoord', function () {
    return view('forgetPasswoord');
});

Route::get('/reset-code-promo', function () {
    $users = DB::table('users')->get();
     
    foreach($users as $user)
    {
        // generate a pin based on 2 * 2 digits + a random character
        $code_rand = mt_rand(10, 99)
                   . mt_rand(10, 99);
       
        //shuffle the result
        $uni_prenom = substr($user->prenom, 0, 1);
        $uni_nom = substr($user->nom, 0, 1);
        $code = strtoupper($uni_nom) . strtoupper($uni_prenom) . $code_rand;

        DB::table('users')->where('id', $user->id)->update(['code_promo' => $code]);
    }
    dd('code promo reset for all users successfully !');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('apprenants', App\Http\Controllers\ApprenantController::class);

Route::resource('/certifications', App\Http\Controllers\CertificationsController::class);

Route::resource('canvaMiniDisqs', App\Http\Controllers\CanvaMiniDisqController::class);

Route::resource('points', App\Http\Controllers\PointsController::class);

Route::resource('passerTests', App\Http\Controllers\PasserTestController::class);


Route::resource('questions', App\Http\Controllers\QuestionController::class);


Route::resource('domaines', App\Http\Controllers\DomaineController::class);


Route::resource('miniDisqs', App\Http\Controllers\MiniDisqController::class);


Route::resource('responses', App\Http\Controllers\ResponseController::class);


Route::resource('responseByUserDiscs', App\Http\Controllers\ResponseByUserDiscController::class);


Route::resource('roueVies', App\Http\Controllers\RoueVieController::class);


Route::resource('responseByUsers', App\Http\Controllers\ResponseByUserController::class);


Route::resource('apprenantDomains', App\Http\Controllers\ApprenantDomainController::class);


Route::resource('caracteristiques', App\Http\Controllers\CaracteristiqueController::class);


Route::resource('videos', App\Http\Controllers\VideoController::class);


Route::resource('audio', App\Http\Controllers\AudioController::class);


Route::resource('articles', App\Http\Controllers\ArticleController::class);


Route::resource('parcoursFormations', App\Http\Controllers\ParcoursFormationController::class);


Route::resource('quizzs', App\Http\Controllers\QuizzController::class);


Route::resource('responsesQuizzs', App\Http\Controllers\ResponsesQuizzController::class);


Route::resource('questionsQuizzs', App\Http\Controllers\QuestionsQuizzController::class);


Route::resource('responseUserQuizzs', App\Http\Controllers\ResponseUserQuizzController::class);


Route::resource('challenges', App\Http\Controllers\challengeController::class);


Route::resource('questionChallenges', App\Http\Controllers\QuestionChallengeController::class);


Route::resource('responseUserChallenges', App\Http\Controllers\ResponseUserChallengeController::class);


Route::resource('commentaires', App\Http\Controllers\CommentaireController::class);


Route::resource('citations', App\Http\Controllers\CitationController::class);



Route::resource('sentMails', App\Http\Controllers\SentMailController::class);


Route::resource('validationEmails', App\Http\Controllers\ValidationEmailController::class);


Route::resource('apprenantCompetences', App\Http\Controllers\ApprenantCompetenceController::class);


Route::resource('competences', App\Http\Controllers\CompetenceController::class);


Route::resource('podcasts', App\Http\Controllers\PodcastController::class);


Route::resource('parcourActivites', App\Http\Controllers\ParcourActiviteController::class);

app/Models/PasserTest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;



/**
 * Class PasserTest
 * @package App\Models
 * @version November 2, 2022, 2:58 am UTC
 *
 * @property integer $roue_de_vie_id
 * @property integer $mini_disq_id
 * @property integer $quizz_id
 * @property integer $competence_id
 * @property integer $user_id
 * @property integer $point_id
 */
class PasserTest extends Model
{


    public $table = 'passer_tests';

    public $fillable = [
        'type',
        'roue_de_vie_id',
        'mini_disc_id',
        'competence_id',
        'quizz_id',
        'challenge_id',
        'podcast_id',
        'user_id',
        'point_id',
        'state'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'roue_de_vie_id' => 'integer',
        'mini_disq_id' => 'integer',
        'quizz_id' => 'integer',
        'competence_id' => 'integer',
        'user_id' => 'integer',
        'point_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'type' => 'required'
    ];

    
}

app/Http/Controllers/PasserTestController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePasserTestRequest;
use App\Http\Requests\UpdatePasserTestRequest;
use App\Repositories\PasserTestRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class PasserTestController extends AppBaseController
{
    /** @var PasserTestRepository $passerTestRepository*/
    private $passerTestRepository;

    public function __construct(PasserTestRepository $passerTestRepo)
    {
        $this->passerTestRepository = $passerTestRepo;
    }

    /**
     * Display a listing of the PasserTest.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $passerTests = $this->passerTestRepository->all();

        return view('passer_tests.index')
            ->with('passerTests', $passerTests);
    }

    /**
     * Show the form for creating a new PasserTest.
     *
     * @return Response
     */
    public function create()
    {
        return view('passer_tests.create');
    }

    /**
     * Store a newly created PasserTest in storage.
     *
     * @param CreatePasserTestRequest $request
     *
     * @return Response
     */
    public function store(CreatePasserTestRequest $request)
    {
        $input = $request->all();

        $passerTest = $this->passerTestRepository->create($input);

        Flash::success('Passer Test saved successfully.');

        return redirect(route('passerTests.index'));
    }

    /**
     * Display the specified PasserTest.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $passerTest = $this->passerTestRepository->find($id);

        if (empty($passerTest)) {
            Flash::error('Passer Test not found');

            return redirect(route('passerTests.index'));
        }

        return view('passer_tests.show')->with('passerTest', $passerTest);
    }

    /**
     * Show the form for editing the specified PasserTest.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $passerTest = $this->passerTestRepository->find($id);

        if (empty($passerTest)) {
            Flash::error('Passer Test not found');

            return redirect(route('passerTests.index'));
        }

        return view('passer_tests.edit')->with('passerTest', $passerTest);
    }

    /**
     * Update the specified PasserTest in storage.
     *
     * @param int $id
     * @param UpdatePasserTestRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePasserTestRequest $request)
    {
        $passerTest = $this->passerTestRepository->find($id);

        if (empty($passerTest)) {
            Flash::error('Passer Test not found');

            return redirect(route('passerTests.index'));
        }

        $passerTest = $this->passerTestRepository->update($request->all(), $id);

        Flash::success('Passer Test updated successfully.');

        return redirect(route('passerTests.index'));
    }

    /**
     * Remove the specified PasserTest from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $passerTest = $this->passerTestRepository->find($id);

        if (empty($passerTest)) {
            Flash::error('Passer Test not found');

            return redirect(route('passerTests.index'));
        }

        $this->passerTestRepository->delete($id);

        Flash::success('Passer Test deleted successfully.');

        return redirect(route('passerTests.index'));
    }
}

resources/views/passer_tests/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Passer Test</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'passerTests.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('passer_tests.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('passerTests.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/passer_tests/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Passer Test</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($passerTest, ['route' => ['passerTests.update', $passerTest->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('passer_tests.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('passerTests.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/passer_tests/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Passer Tests</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('passerTests.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('passer_tests.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/passer_tests/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Passer Test Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('passerTests.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('passer_tests.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/passer_tests/show_fields.blade.php
<!-- Roue De Vie Id Field -->
<div class="col-sm-12">
    {!! Form::label('roue_de_vie_id', 'Roue De Vie Id:') !!}
    <p>{{ $passerTest->roue_de_vie_id }}</p>
</div>

<!-- Canva Mini Disq Id Field -->
<div class="col-sm-12">
    {!! Form::label('canva_mini_disq_id', 'Canva Mini Disq Id:') !!}
    <p>{{ $passerTest->canva_mini_disq_id }}</p>
</div>

<!-- Quizz Id Field -->
<div class="col-sm-12">
    {!! Form::label('quizz_id', 'Quizz Id:') !!}
    <p>{{ $passerTest->quizz_id }}</p>
</div>

<!-- Competence Id Field -->
<div class="col-sm-12">
    {!! Form::label('competence_id', 'Competence Id:') !!}
    <p>{{ $passerTest->competence_id }}</p>
</div>

<!-- User Id Field -->
<div class="col-sm-12">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{{ $passerTest->user_id }}</p>
</div>

<!-- Point Id Field -->
<div class="col-sm-12">
    {!! Form::label('point_id', 'Point Id:') !!}
    <p>{{ $passerTest->point_id }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $passerTest->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $passerTest->updated_at }}</p>
</div>

resources/views/passer_tests/table.blade.php
<div class="table-responsive">
    <table class="table" id="passerTests-table">
        <thead>
        <tr>
            <th>Roue De Vie Id</th>
        <th>Canva Mini Disq Id</th>
        <th>Quizz Id</th>
        <th>Competence Id</th>
        <th>User Id</th>
        <th>Point Id</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($passerTests as $passerTest)
            <tr>
                <td>{{ $passerTest->roue_de_vie_id }}</td>
            <td>{{ $passerTest->canva_mini_disq_id }}</td>
            <td>{{ $passerTest->quizz_id }}</td>
            <td>{{ $passerTest->competence_id }}</td>
            <td>{{ $passerTest->user_id }}</td>
            <td>{{ $passerTest->point_id }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['passerTests.destroy', $passerTest->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('passerTests.show', [$passerTest->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('passerTests.edit', [$passerTest->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>